//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public Answers()
        {
            this.Questions = new HashSet<Questions>();
            this.Questions1 = new HashSet<Questions>();
        }
    
        public int A_Id { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<Questions> Questions1 { get; set; }
    }
}
