//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Games = new HashSet<Games>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int C_Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Games> Games { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
