//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Players = new HashSet<Players>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int G_Id { get; set; }
        public string Name { get; set; }
        public int Turns { get; set; }
        public int PlayerTurn { get; set; }
        public int TurnNumber { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Players> Players { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
