//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Answers1 = new HashSet<Answers>();
            this.Games = new HashSet<Games>();
        }
    
        public int Q_Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual ICollection<Answers> Answers1 { get; set; }
        public virtual ICollection<Games> Games { get; set; }
    }
}
